#! /bin/sh
# /etc/init.d/branly-gateway
#
### BEGIN INIT INFO
# Provides:          branly-gateway
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start or stop the branly gateway daemon.
### END INIT INFO

case "$1" in
  start)
    /home/pi/branly-gateway.py &
    ;;
  stop)
    killall branly-gateway.py
    ;;
  *)
    echo "Usage: /etc/init.d/branly-gateway {start|stop}"
    exit 1
    ;;
esac
 
exit 0
